// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('agileMetrics').factory('elasticsearch', function($http) {
    var elasticObject;
    elasticObject = {
      post: function(config) {
        return this.query('POST', config);
      },
      query: function(method, config) {
        var properties;
        properties = {
          method: method.toUpperCase(),
          url: config.url,
          data: config.query
        };
        return $http(properties);
      },
      "delete": function(url) {
        var properties;
        properties = {
          method: 'DELETE',
          url: url
        };
        return $http(properties);
      }
    };
    return elasticObject;
  });

}).call(this);
